USE TaranTuvi;

-- Eliminar tablas dependientes primero
DROP TABLE IF EXISTS VALORACION;
DROP TABLE IF EXISTS PELICULALISTAPELICULA;
DROP TABLE IF EXISTS LISTAPELICULA;
DROP TABLE IF EXISTS TRABAJO;
DROP TABLE IF EXISTS ACTUACION;
DROP TABLE IF EXISTS PELICULAPAISRODAJE;
DROP TABLE IF EXISTS PELICULAPRODUCTORA;
DROP TABLE IF EXISTS PELICULAIDIOMAHABLADO;
DROP TABLE IF EXISTS PELICULAPALABRACLAVE;
DROP TABLE IF EXISTS PELICULAGENEROPELICULA;

-- Luego las tablas principales
DROP TABLE IF EXISTS PELICULA;
DROP TABLE IF EXISTS PRODUCTORA;
DROP TABLE IF EXISTS PAISRODAJE;
DROP TABLE IF EXISTS PERSONA;
DROP TABLE IF EXISTS DEPARTAMENTO;
DROP TABLE IF EXISTS NACIONALIDAD;
DROP TABLE IF EXISTS GENEROPERSONA;
DROP TABLE IF EXISTS IDIOMAHABLADO;
DROP TABLE IF EXISTS PALABRACLAVE;
DROP TABLE IF EXISTS GENEROPELICULA;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS ROL;
