USE TaranTuvi;

CREATE TABLE `PELICULA` (
	`PELICULAID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`TITULOORIGINAL` VARCHAR(255),
	`IDIOMAORIGINALHABLADOID` INT,
	`PRESUPUESTO` DECIMAL,
	`FECHAESTRENO` DATE,
	`DURACION` INT,
	`RECAUDACION` DECIMAL,
	`ESTADO` VARCHAR(255),
	`PAGINAWEB` TEXT,
	`DESCRIPCION` TEXT,
	`ESLOGAN` VARCHAR(255),
	`URLCARATULA` TEXT,
	`VOTOS` INT,
	`NOTA` DECIMAL,
	`POPULARIDAD` DECIMAL,
	PRIMARY KEY(`PELICULAID`)
);


CREATE TABLE `NACIONALIDAD` (
	`NACIONALIDADID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`NACIONALIDADNOMBRE` VARCHAR(50),
	PRIMARY KEY(`NACIONALIDADID`)
);


CREATE TABLE `USUARIO` (
	`USUARIOID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`NOMBRE` VARCHAR(255),
	`ROLID` INT,
	`PASSWORDHASH` TEXT(65535) NOT NULL,
	`SALT` TEXT(65535) NOT NULL,
	PRIMARY KEY(`USUARIOID`)
);


CREATE TABLE `ROL` (
	`ROLID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`ROLNOMBRE` VARCHAR(255),
	PRIMARY KEY(`ROLID`)
);


CREATE TABLE `GENEROPELICULA` (
	`GENEROPELICULAID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`GENERONOMBRE` VARCHAR(255),
	PRIMARY KEY(`GENEROPELICULAID`)
);


CREATE TABLE `PALABRACLAVE` (
	`PALABRACLAVEID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`PALABRACLAVENOMBRE` VARCHAR(255),
	PRIMARY KEY(`PALABRACLAVEID`)
);


CREATE TABLE `IDIOMAHABLADO` (
	`IDIOMAHABLADOID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`IDIOMAHABLADONOMBRE` VARCHAR(255),
	PRIMARY KEY(`IDIOMAHABLADOID`)
);


CREATE TABLE `GENEROPERSONA` (
	`GENEROPERSONAID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`GENEROPERSONANOMBRE` VARCHAR(255),
	PRIMARY KEY(`GENEROPERSONAID`)
);


CREATE TABLE `DEPARTAMENTO` (
	`DEPARTAMENTOID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`DEPARTAMENTONOMBRE` VARCHAR(255),
	PRIMARY KEY(`DEPARTAMENTOID`)
);


CREATE TABLE `ACTUACION` (
	`PERSONAID` INT,
	`PELICULAID` INT,
	`GENEROPERSONAID` INT,
	`PERSONAJE` VARCHAR(255),
	`ACTUACIONID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`ORDEN` INT,
	PRIMARY KEY(`ACTUACIONID`)
);


CREATE TABLE `PELICULAGENEROPELICULA` (
	`GENEROPELICULAID` INT NOT NULL,
	`PELICULAID` INT NOT NULL,
	PRIMARY KEY(`GENEROPELICULAID`, `PELICULAID`)
);


CREATE TABLE `PELICULAPALABRACLAVE` (
	`PALABRACLAVEID` INT NOT NULL,
	`PELICULAID` INT NOT NULL,
	PRIMARY KEY(`PALABRACLAVEID`, `PELICULAID`)
);


CREATE TABLE `PELICULAIDIOMAHABLADO` (
	`IDIOMAHABLADOID` INT NOT NULL,
	`PELICULAID` INT NOT NULL,
	PRIMARY KEY(`IDIOMAHABLADOID`, `PELICULAID`)
);


CREATE TABLE `TRABAJO` (
	`TRABAJOID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`PERSONAID` INT,
	`PELICULAID` INT,
	`TRABAJONOMBRE` VARCHAR(255),
	`DEPARTAMENTOID` INT,
	PRIMARY KEY(`TRABAJOID`)
);


CREATE TABLE `PRODUCTORA` (
	`PRODUCTORAID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`PRODUCTORANOMBRE` VARCHAR(255),
	PRIMARY KEY(`PRODUCTORAID`)
);


CREATE TABLE `PAISRODAJE` (
	`PAISRODAJEID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`PAISRODAJENOMBRE` VARCHAR(255),
	PRIMARY KEY(`PAISRODAJEID`)
);


CREATE TABLE `PELICULAPAISRODAJE` (
	`PELICULAID` INT NOT NULL,
	`PAISRODAJEID` INT NOT NULL,
	PRIMARY KEY(`PELICULAID`, `PAISRODAJEID`)
);


CREATE TABLE `PELICULAPRODUCTORA` (
	`PELICULAID` INT NOT NULL,
	`PRODUCTORAID` INT NOT NULL,
	PRIMARY KEY(`PELICULAID`, `PRODUCTORAID`)
);


CREATE TABLE `PERSONA` (
	`PERSONAID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`NOMBRE` VARCHAR(255),
	`GENEROPERSONAID` INT,
	`NACIONALIDADID` INT,
	`URLFOTO` TEXT,
	PRIMARY KEY(`PERSONAID`)
);


CREATE TABLE `LISTAPELICULA` (
	`LISTAPELICULAID` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`LISTAPELICULANOMBRE` VARCHAR(255),
	`USUARIOID` INT,
	PRIMARY KEY(`LISTAPELICULAID`)
);


CREATE TABLE `VALORACION` (
	`PELICULAID` INT,
	`USUARIOID` INT,
	`NOTA` DECIMAL,
	`VALORACIONID` INT NOT NULL,
	PRIMARY KEY(`VALORACIONID`)
);


CREATE TABLE `PELICULALISTAPELICULA` (
	`PELICULAID` INT NOT NULL,
	`LISTAPELICULAID` INT NOT NULL,
	PRIMARY KEY(`PELICULAID`, `LISTAPELICULAID`)
);


ALTER TABLE `TRABAJO`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TRABAJO`
ADD FOREIGN KEY(`DEPARTAMENTOID`) REFERENCES `DEPARTAMENTO`(`DEPARTAMENTOID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAPAISRODAJE`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAPAISRODAJE`
ADD FOREIGN KEY(`PAISRODAJEID`) REFERENCES `PAISRODAJE`(`PAISRODAJEID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAPRODUCTORA`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ACTUACION`
ADD FOREIGN KEY(`GENEROPERSONAID`) REFERENCES `GENEROPERSONA`(`GENEROPERSONAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `TRABAJO`
ADD FOREIGN KEY(`PERSONAID`) REFERENCES `PERSONA`(`PERSONAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ACTUACION`
ADD FOREIGN KEY(`PERSONAID`) REFERENCES `PERSONA`(`PERSONAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PERSONA`
ADD FOREIGN KEY(`GENEROPERSONAID`) REFERENCES `GENEROPERSONA`(`GENEROPERSONAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PERSONA`
ADD FOREIGN KEY(`NACIONALIDADID`) REFERENCES `NACIONALIDAD`(`NACIONALIDADID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `USUARIO`
ADD FOREIGN KEY(`ROLID`) REFERENCES `ROL`(`ROLID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAIDIOMAHABLADO`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAIDIOMAHABLADO`
ADD FOREIGN KEY(`IDIOMAHABLADOID`) REFERENCES `IDIOMAHABLADO`(`IDIOMAHABLADOID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAPALABRACLAVE`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAPALABRACLAVE`
ADD FOREIGN KEY(`PALABRACLAVEID`) REFERENCES `PALABRACLAVE`(`PALABRACLAVEID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAGENEROPELICULA`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAGENEROPELICULA`
ADD FOREIGN KEY(`GENEROPELICULAID`) REFERENCES `GENEROPELICULA`(`GENEROPELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `ACTUACION`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `VALORACION`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `VALORACION`
ADD FOREIGN KEY(`USUARIOID`) REFERENCES `USUARIO`(`USUARIOID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `LISTAPELICULA`
ADD FOREIGN KEY(`USUARIOID`) REFERENCES `USUARIO`(`USUARIOID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULALISTAPELICULA`
ADD FOREIGN KEY(`PELICULAID`) REFERENCES `PELICULA`(`PELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULALISTAPELICULA`
ADD FOREIGN KEY(`LISTAPELICULAID`) REFERENCES `LISTAPELICULA`(`LISTAPELICULAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULAPRODUCTORA`
ADD FOREIGN KEY(`PRODUCTORAID`) REFERENCES `PRODUCTORA`(`PRODUCTORAID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `PELICULA`
ADD FOREIGN KEY(`IDIOMAORIGINALHABLADOID`) REFERENCES `IDIOMAHABLADO`(`IDIOMAHABLADOID`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
